data = [
  { "id": 0, "piece": "C", "team": " red", "hasPiece": True },
  { "id": 1, "piece": "H", "team": " red", "hasPiece": True },
  { "id": 2, "piece": "E", "team": " red", "hasPiece": True },
  { "id": 3, "piece": "A", "team": " red", "hasPiece": True },
  { "id": 4, "piece": "G", "team": " red", "hasPiece": True },
  { "id": 5, "piece": "A", "team": " red", "hasPiece": True },
  { "id": 6, "piece": "E", "team": " red", "hasPiece": True },
  { "id": 7, "piece": "H", "team": " red", "hasPiece": True },
  { "id": 8, "piece": "C", "team": " red", "hasPiece": True },
  { "id": 9, "piece": "", "team": "", "hasPiece": False },
  { "id": 10, "piece": "", "team": "", "hasPiece": False },
  { "id": 11, "piece": "", "team": "", "hasPiece": False },
  { "id": 12, "piece": "", "team": "", "hasPiece": False },
  { "id": 13, "piece": "", "team": "", "hasPiece": False },
  { "id": 14, "piece": "", "team": "", "hasPiece": False },
  { "id": 15, "piece": "", "team": "", "hasPiece": False },
  { "id": 16, "piece": "", "team": "", "hasPiece": False },
  { "id": 17, "piece": "", "team": "", "hasPiece": False },
  { "id": 18, "piece": "", "team": "", "hasPiece": False },
  { "id": 19, "piece": "P", "team": " red", "hasPiece": True },
  { "id": 20, "piece": "", "team": "", "hasPiece": False },
  { "id": 21, "piece": "", "team": "", "hasPiece": False },
  { "id": 22, "piece": "", "team": "", "hasPiece": False },
  { "id": 23, "piece": "", "team": "", "hasPiece": False },
  { "id": 24, "piece": "", "team": "", "hasPiece": False },
  { "id": 25, "piece": "P", "team": " red", "hasPiece": True },
  { "id": 26, "piece": "", "team": "", "hasPiece": False },
  { "id": 27, "piece": "S", "team": " red", "hasPiece": True },
  { "id": 28, "piece": "", "team": "", "hasPiece": False },
  { "id": 29, "piece": "S", "team": " red", "hasPiece": True },
  { "id": 30, "piece": "", "team": "", "hasPiece": False },
  { "id": 31, "piece": "S", "team": " red", "hasPiece": True },
  { "id": 32, "piece": "", "team": "", "hasPiece": False },
  { "id": 33, "piece": "S", "team": " red", "hasPiece": True },
  { "id": 34, "piece": "", "team": "", "hasPiece": False },
  { "id": 35, "piece": "S", "team": " red", "hasPiece": True },
  { "id": 36, "piece": "", "team": "", "hasPiece": False },
  { "id": 37, "piece": "", "team": "", "hasPiece": False },
  { "id": 38, "piece": "", "team": "", "hasPiece": False },
  { "id": 39, "piece": "", "team": "", "hasPiece": False },
  { "id": 40, "piece": "", "team": "", "hasPiece": False },
  { "id": 41, "piece": "", "team": "", "hasPiece": False },
  { "id": 42, "piece": "", "team": "", "hasPiece": False },
  { "id": 43, "piece": "", "team": "", "hasPiece": False },
  { "id": 44, "piece": "", "team": "", "hasPiece": False },
  { "id": 45, "piece": "", "team": "", "hasPiece": False },
  { "id": 46, "piece": "", "team": "", "hasPiece": False },
  { "id": 47, "piece": "", "team": "", "hasPiece": False },
  { "id": 48, "piece": "", "team": "", "hasPiece": False },
  { "id": 49, "piece": "", "team": "", "hasPiece": False },
  { "id": 50, "piece": "", "team": "", "hasPiece": False },
  { "id": 51, "piece": "", "team": "", "hasPiece": False },
  { "id": 52, "piece": "", "team": "", "hasPiece": False },
  { "id": 53, "piece": "", "team": "", "hasPiece": False },
  { "id": 54, "piece": "S", "team": " black", "hasPiece": True },
  { "id": 55, "piece": "", "team": "", "hasPiece": False },
  { "id": 56, "piece": "S", "team": " black", "hasPiece": True },
  { "id": 57, "piece": "", "team": "", "hasPiece": False },
  { "id": 58, "piece": "S", "team": " black", "hasPiece": True },
  { "id": 59, "piece": "", "team": "", "hasPiece": False },
  { "id": 60, "piece": "S", "team": " black", "hasPiece": True },
  { "id": 61, "piece": "", "team": "", "hasPiece": False },
  { "id": 62, "piece": "S", "team": " black", "hasPiece": True },
  { "id": 63, "piece": "", "team": "", "hasPiece": False },
  { "id": 64, "piece": "P", "team": " black", "hasPiece": True },
  { "id": 65, "piece": "", "team": "", "hasPiece": False },
  { "id": 66, "piece": "", "team": "", "hasPiece": False },
  { "id": 67, "piece": "", "team": "", "hasPiece": False },
  { "id": 68, "piece": "", "team": "", "hasPiece": False },
  { "id": 69, "piece": "", "team": "", "hasPiece": False },
  { "id": 70, "piece": "P", "team": " black", "hasPiece": True },
  { "id": 71, "piece": "", "team": "", "hasPiece": False },
  { "id": 72, "piece": "", "team": "", "hasPiece": False },
  { "id": 73, "piece": "", "team": "", "hasPiece": False },
  { "id": 74, "piece": "", "team": "", "hasPiece": False },
  { "id": 75, "piece": "", "team": "", "hasPiece": False },
  { "id": 76, "piece": "", "team": "", "hasPiece": False },
  { "id": 77, "piece": "", "team": "", "hasPiece": False },
  { "id": 78, "piece": "", "team": "", "hasPiece": False },
  { "id": 79, "piece": "", "team": "", "hasPiece": False },
  { "id": 80, "piece": "", "team": "", "hasPiece": False },
  { "id": 81, "piece": "C", "team": " black", "hasPiece": True },
  { "id": 82, "piece": "H", "team": " black", "hasPiece": True },
  { "id": 83, "piece": "E", "team": " black", "hasPiece": True },
  { "id": 84, "piece": "A", "team": " black", "hasPiece": True },
  { "id": 85, "piece": "G", "team": " black", "hasPiece": True },
  { "id": 86, "piece": "A", "team": " black", "hasPiece": True },
  { "id": 87, "piece": "E", "team": " black", "hasPiece": True },
  { "id": 88, "piece": "H", "team": " black", "hasPiece": True },
  { "id": 89, "piece": "C", "team": " black", "hasPiece": True },
]

for i in data:
    i["isMoveable"] = False
import json
print(json.dumps(data))