let data = [
  { id: 0, piece: "C", team: "red", hasPiece: true },
  { id: 1, piece: "H", team: "red", hasPiece: true },
  { id: 2, piece: "E", team: "red", hasPiece: true },
  { id: 3, piece: "A", team: "red", hasPiece: true },
  { id: 4, piece: "G", team: "red", hasPiece: true },
  { id: 5, piece: "A", team: "red", hasPiece: true },
  { id: 6, piece: "E", team: "red", hasPiece: true },
  { id: 7, piece: "H", team: "red", hasPiece: true },
  { id: 8, piece: "C", team: "red", hasPiece: true },
  { id: 9, piece: "", team: "", hasPiece: false },
  { id: 10, piece: "", team: "", hasPiece: false },
  { id: 11, piece: "", team: "", hasPiece: false },
  { id: 12, piece: "", team: "", hasPiece: false },
  { id: 13, piece: "", team: "", hasPiece: false },
  { id: 14, piece: "", team: "", hasPiece: false },
  { id: 15, piece: "", team: "", hasPiece: false },
  { id: 16, piece: "", team: "", hasPiece: false },
  { id: 17, piece: "", team: "", hasPiece: false },
  { id: 18, piece: "", team: "", hasPiece: false },
  { id: 19, piece: "P", team: "red", hasPiece: true },
  { id: 20, piece: "", team: "", hasPiece: false },
  { id: 21, piece: "", team: "", hasPiece: false },
  { id: 22, piece: "", team: "", hasPiece: false },
  { id: 23, piece: "", team: "", hasPiece: false },
  { id: 24, piece: "", team: "", hasPiece: false },
  { id: 25, piece: "P", team: "red", hasPiece: true },
  { id: 26, piece: "", team: "", hasPiece: false },
  { id: 27, piece: "S", team: "red", hasPiece: true },
  { id: 28, piece: "", team: "", hasPiece: false },
  { id: 29, piece: "S", team: "red", hasPiece: true },
  { id: 30, piece: "", team: "", hasPiece: false },
  { id: 31, piece: "S", team: "red", hasPiece: true },
  { id: 32, piece: "", team: "", hasPiece: false },
  { id: 33, piece: "S", team: "red", hasPiece: true },
  { id: 34, piece: "", team: "", hasPiece: false },
  { id: 35, piece: "S", team: "red", hasPiece: true },
  { id: 36, piece: "", team: "", hasPiece: false },
  { id: 37, piece: "", team: "", hasPiece: false },
  { id: 38, piece: "", team: "", hasPiece: false },
  { id: 39, piece: "", team: "", hasPiece: false },
  { id: 40, piece: "", team: "", hasPiece: false },
  { id: 41, piece: "", team: "", hasPiece: false },
  { id: 42, piece: "", team: "", hasPiece: false },
  { id: 43, piece: "", team: "", hasPiece: false },
  { id: 44, piece: "", team: "", hasPiece: false },
  { id: 45, piece: "", team: "", hasPiece: false },
  { id: 46, piece: "", team: "", hasPiece: false },
  { id: 47, piece: "", team: "", hasPiece: false },
  { id: 48, piece: "", team: "", hasPiece: false },
  { id: 49, piece: "", team: "", hasPiece: false },
  { id: 50, piece: "", team: "", hasPiece: false },
  { id: 51, piece: "", team: "", hasPiece: false },
  { id: 52, piece: "", team: "", hasPiece: false },
  { id: 53, piece: "", team: "", hasPiece: false },
  { id: 54, piece: "S", team: " black", hasPiece: true },
  { id: 55, piece: "", team: "", hasPiece: false },
  { id: 56, piece: "S", team: " black", hasPiece: true },
  { id: 57, piece: "", team: "", hasPiece: false },
  { id: 58, piece: "S", team: " black", hasPiece: true },
  { id: 59, piece: "", team: "", hasPiece: false },
  { id: 60, piece: "S", team: " black", hasPiece: true },
  { id: 61, piece: "", team: "", hasPiece: false },
  { id: 62, piece: "S", team: " black", hasPiece: true },
  { id: 63, piece: "", team: "", hasPiece: false },
  { id: 64, piece: "P", team: " black", hasPiece: true },
  { id: 65, piece: "", team: "", hasPiece: false },
  { id: 66, piece: "", team: "", hasPiece: false },
  { id: 67, piece: "", team: "", hasPiece: false },
  { id: 68, piece: "", team: "", hasPiece: false },
  { id: 69, piece: "", team: "", hasPiece: false },
  { id: 70, piece: "P", team: " black", hasPiece: true },
  { id: 71, piece: "", team: "", hasPiece: false },
  { id: 72, piece: "", team: "", hasPiece: false },
  { id: 73, piece: "", team: "", hasPiece: false },
  { id: 74, piece: "", team: "", hasPiece: false },
  { id: 75, piece: "", team: "", hasPiece: false },
  { id: 76, piece: "", team: "", hasPiece: false },
  { id: 77, piece: "", team: "", hasPiece: false },
  { id: 78, piece: "", team: "", hasPiece: false },
  { id: 79, piece: "", team: "", hasPiece: false },
  { id: 80, piece: "", team: "", hasPiece: false },
  { id: 81, piece: "C", team: " black", hasPiece: true },
  { id: 82, piece: "H", team: " black", hasPiece: true },
  { id: 83, piece: "E", team: " black", hasPiece: true },
  { id: 84, piece: "A", team: " black", hasPiece: true },
  { id: 85, piece: "G", team: " black", hasPiece: true },
  { id: 86, piece: "A", team: " black", hasPiece: true },
  { id: 87, piece: "E", team: " black", hasPiece: true },
  { id: 88, piece: "H", team: " black", hasPiece: true },
  { id: 89, piece: "C", team: " black", hasPiece: true },
];

export default data;
