let data = [
  [
    { type: "Chariot", img: "車", team: "red", row: 0, col: 0 },
    { type: "Horse", img: "馬", team: "red", row: 0, col: 1 },
    { type: "Elephant", img: "相", team: "red", row: 0, col: 2 },
    { type: "Advisor", img: "仕", team: "red", row: 0, col: 3 },
    { type: "General", img: "帥", team: "red", row: 0, col: 4 },
    { type: "Advisor", img: "仕", team: "red", row: 0, col: 5 },
    { type: "Elephant", img: "相", team: "red", row: 0, col: 6 },
    { type: "Horse", img: "馬", team: "red", row: 0, col: 7 },
    { type: "Chariot", img: "車", team: "red", row: 0, col: 8 },
  ],
  Array(9).fill(null),
  [
    null,
    { type: "Cannon", img: "炮", team: "red", row: 2, col: 1 },
    null,
    null,
    null,
    null,
    null,
    { type: "Cannon", img: "炮", team: "red", row: 2, col: 7 },
    null,
  ],
  [
    {
      type: "Soldier",
      img: "兵",
      team: "red",
      row: 3,
      col: 0,
      hasCrossed: false,
    },
    null,
    {
      type: "Soldier",
      img: "兵",
      team: "red",
      row: 3,
      col: 2,
      hasCrossed: false,
    },
    null,
    {
      type: "Soldier",
      img: "兵",
      team: "red",
      row: 3,
      col: 4,
      hasCrossed: false,
    },
    null,
    {
      type: "Soldier",
      img: "兵",
      team: "red",
      row: 3,
      col: 6,
      hasCrossed: false,
    },
    null,
    {
      type: "Soldier",
      img: "兵",
      team: "red",
      row: 3,
      col: 8,
      hasCrossed: false,
    },
  ],
  Array(9).fill(null),
  Array(9).fill(null),
  [
    {
      type: "Soldier",
      img: "卒",
      team: " black",
      row: 6,
      col: 0,
      hasCrossed: false,
    },
    null,
    {
      type: "Soldier",
      img: "卒",
      team: " black",
      row: 6,
      col: 2,
      hasCrossed: false,
    },
    null,
    {
      type: "Soldier",
      img: "卒",
      team: " black",
      row: 6,
      col: 4,
      hasCrossed: false,
    },
    null,
    {
      type: "Soldier",
      img: "卒",
      team: " black",
      row: 6,
      col: 6,
      hasCrossed: false,
    },
    null,
    {
      type: "Soldier",
      img: "卒",
      team: " black",
      row: 6,
      col: 8,
      hasCrossed: false,
    },
  ],
  [
    null,
    { type: "Cannon", img: "炮", team: " black", row: 7, col: 1 },
    null,
    null,
    null,
    null,
    null,
    { type: "Cannon", img: "炮", team: " black", row: 7, col: 7 },
    null,
  ],
  Array(9).fill(null),
  [
    { type: "Chariot", img: "車", team: " black", row: 9, col: 0 },
    { type: "Horse", img: "馬", team: " black", row: 9, col: 1 },
    { type: "Elephant", img: "象", team: " black", row: 9, col: 2 },
    { type: "Advisor", img: "士", team: " black", row: 9, col: 3 },
    { type: "General", img: "將", team: " black", row: 9, col: 4 },
    { type: "Advisor", img: "士", team: " black", row: 9, col: 5 },
    { type: "Elephant", img: "象", team: " black", row: 9, col: 6 },
    { type: "Horse", img: "馬", team: " black", row: 9, col: 7 },
    { type: "Chariot", img: "車", team: " black", row: 9, col: 8 },
  ],
];

export default data;
