import { NPiece, Team } from "./types";

let data: NPiece[][] = [
  [
    {
      id: "Left Chariot",
      type: "Chariot",
      img: "車",
      team: Team.red,
      row: 0,
      col: 0,
    },
    {
      id: "Left Horse",
      type: "Horse",
      img: "馬",
      team: Team.red,
      row: 0,
      col: 1,
    },
    {
      id: "Left Elephant",
      type: "Elephant",
      img: "相",
      team: Team.red,
      row: 0,
      col: 2,
    },
    {
      id: "Left Advisor",
      type: "Advisor",
      img: "仕",
      team: Team.red,
      row: 0,
      col: 3,
    },
    {
      id: "General",
      type: "General",
      img: "帥",
      team: Team.red,
      row: 0,
      col: 4,
    },
    {
      id: "Right Advisor",
      type: "Advisor",
      img: "仕",
      team: Team.red,
      row: 0,
      col: 5,
    },
    {
      id: "Right Elephant",
      type: "Elephant",
      img: "相",
      team: Team.red,
      row: 0,
      col: 6,
    },
    {
      id: "Right Horse",
      type: "Horse",
      img: "馬",
      team: Team.red,
      row: 0,
      col: 7,
    },
    {
      id: "Right Chariot",
      type: "Chariot",
      img: "車",
      team: Team.red,
      row: 0,
      col: 8,
    },
  ],
  Array(9).fill(null),
  [
    null,
    {
      id: "Left Cannon",
      type: "Cannon",
      img: "炮",
      team: Team.red,
      row: 2,
      col: 1,
    },
    null,
    null,
    null,
    null,
    null,
    {
      id: "Right Cannon",
      type: "Cannon",
      img: "炮",
      team: Team.red,
      row: 2,
      col: 7,
    },
    null,
  ],
  [
    {
      id: "Soldier #1",
      type: "Soldier",
      img: "兵",
      team: Team.red,
      row: 3,
      col: 0,
    },
    null,
    {
      id: "Soldier #2",
      type: "Soldier",
      img: "兵",
      team: Team.red,
      row: 3,
      col: 2,
    },
    null,
    {
      id: "Soldier #3",
      type: "Soldier",
      img: "兵",
      team: Team.red,
      row: 3,
      col: 4,
    },
    null,
    {
      id: "Soldier #4",
      type: "Soldier",
      img: "兵",
      team: Team.red,
      row: 3,
      col: 6,
    },
    null,
    {
      id: "Soldier #5",
      type: "Soldier",
      img: "兵",
      team: Team.red,
      row: 3,
      col: 8,
    },
  ],
  Array(9).fill(null),
  Array(9).fill(null),
  [
    {
      id: "Soldier #5",
      type: "Soldier",
      img: "卒",
      team: Team.black,
      row: 6,
      col: 0,
    },
    null,
    {
      id: "Soldier #4",
      type: "Soldier",
      img: "卒",
      team: Team.black,
      row: 6,
      col: 2,
    },
    null,
    {
      id: "Soldier #3",
      type: "Soldier",
      img: "卒",
      team: Team.black,
      row: 6,
      col: 4,
    },
    null,
    {
      id: "Soldier #2",
      type: "Soldier",
      img: "卒",
      team: Team.black,
      row: 6,
      col: 6,
    },
    null,
    {
      id: "Soldier #1",
      type: "Soldier",
      img: "卒",
      team: Team.black,
      row: 6,
      col: 8,
    },
  ],
  [
    null,
    {
      id: "Right Cannon",
      type: "Cannon",
      img: "炮",
      team: Team.black,
      row: 7,
      col: 1,
    },
    null,
    null,
    null,
    null,
    null,
    {
      id: "Left Cannon",
      type: "Cannon",
      img: "炮",
      team: Team.black,
      row: 7,
      col: 7,
    },
    null,
  ],
  Array(9).fill(null),
  [
    {
      id: "Right Chariot",
      type: "Chariot",
      img: "車",
      team: Team.black,
      row: 9,
      col: 0,
    },
    {
      id: "Right Horse",
      type: "Horse",
      img: "馬",
      team: Team.black,
      row: 9,
      col: 1,
    },
    {
      id: "Right Elephant",
      type: "Elephant",
      img: "象",
      team: Team.black,
      row: 9,
      col: 2,
    },
    {
      id: "Right Advisor",
      type: "Advisor",
      img: "士",
      team: Team.black,
      row: 9,
      col: 3,
    },
    {
      id: "General",
      type: "General",
      img: "將",
      team: Team.black,
      row: 9,
      col: 4,
    },
    {
      id: "Left Advisor",
      type: "Advisor",
      img: "士",
      team: Team.black,
      row: 9,
      col: 5,
    },
    {
      id: "Left Elephant",
      type: "Elephant",
      img: "象",
      team: Team.black,
      row: 9,
      col: 6,
    },
    {
      id: "Left Horse",
      type: "Horse",
      img: "馬",
      team: Team.black,
      row: 9,
      col: 7,
    },
    {
      id: "Left Chariot",
      type: "Chariot",
      img: "車",
      team: Team.black,
      row: 9,
      col: 8,
    },
  ],
];

export default data;
