import { NPiece, Team } from "./types";

let data: NPiece[][] = [
  [
    {
      id: "leftChariot",
      type: "Chariot",
      img: "車",
      team: Team.red,
      row: 0,
      col: 0,
    },
    {
      id: "leftHorse",
      type: "Horse",
      img: "馬",
      team: Team.red,
      row: 0,
      col: 1,
    },
    {
      id: "leftElephant",
      type: "Elephant",
      img: "相",
      team: Team.red,
      row: 0,
      col: 2,
    },
    {
      id: "leftAdvisor",
      type: "Advisor",
      img: "仕",
      team: Team.red,
      row: 0,
      col: 3,
    },
    {
      id: "general",
      type: "General",
      img: "帥",
      team: Team.red,
      row: 0,
      col: 4,
    },
    {
      id: "rightAdvisor",
      type: "Advisor",
      img: "仕",
      team: Team.red,
      row: 0,
      col: 5,
    },
    {
      id: "rightElephant",
      type: "Elephant",
      img: "相",
      team: Team.red,
      row: 0,
      col: 6,
    },
    {
      id: "rightHorse",
      type: "Horse",
      img: "馬",
      team: Team.red,
      row: 0,
      col: 7,
    },
    {
      id: "rightChariot",
      type: "Chariot",
      img: "車",
      team: Team.red,
      row: 0,
      col: 8,
    },
  ],
  Array(9).fill(null),
  [
    null,
    {
      id: "leftCannon",
      type: "Cannon",
      img: "炮",
      team: Team.red,
      row: 2,
      col: 1,
    },
    null,
    null,
    null,
    null,
    null,
    {
      id: "rightCannon",
      type: "Cannon",
      img: "炮",
      team: Team.red,
      row: 2,
      col: 7,
    },
    null,
  ],
  [
    {
      id: "Soldier1",
      type: "Soldier",
      img: "兵",
      team: Team.red,
      row: 3,
      col: 0,
    },
    null,
    {
      id: "Soldier2",
      type: "Soldier",
      img: "兵",
      team: Team.red,
      row: 3,
      col: 2,
    },
    null,
    {
      id: "Soldier3",
      type: "Soldier",
      img: "兵",
      team: Team.red,
      row: 3,
      col: 4,
    },
    null,
    {
      id: "Soldier4",
      type: "Soldier",
      img: "兵",
      team: Team.red,
      row: 3,
      col: 6,
    },
    null,
    {
      id: "Soldier5",
      type: "Soldier",
      img: "兵",
      team: Team.red,
      row: 3,
      col: 8,
    },
  ],
  Array(9).fill(null),
  Array(9).fill(null),
  [
    {
      id: "Soldier5",
      type: "Soldier",
      img: "卒",
      team: Team.black,
      row: 6,
      col: 0,
    },
    null,
    {
      id: "Soldier4",
      type: "Soldier",
      img: "卒",
      team: Team.black,
      row: 6,
      col: 2,
    },
    null,
    {
      id: "Soldier3",
      type: "Soldier",
      img: "卒",
      team: Team.black,
      row: 6,
      col: 4,
    },
    null,
    {
      id: "Soldier2",
      type: "Soldier",
      img: "卒",
      team: Team.black,
      row: 6,
      col: 6,
    },
    null,
    {
      id: "Soldier1",
      type: "Soldier",
      img: "卒",
      team: Team.black,
      row: 6,
      col: 8,
    },
  ],
  [
    null,
    {
      id: "rightCannon",
      type: "Cannon",
      img: "炮",
      team: Team.black,
      row: 7,
      col: 1,
    },
    null,
    null,
    null,
    null,
    null,
    {
      id: "leftCannon",
      type: "Cannon",
      img: "炮",
      team: Team.black,
      row: 7,
      col: 7,
    },
    null,
  ],
  Array(9).fill(null),
  [
    {
      id: "rightChariot",
      type: "Chariot",
      img: "車",
      team: Team.black,
      row: 9,
      col: 0,
    },
    {
      id: "rightHorse",
      type: "Horse",
      img: "馬",
      team: Team.black,
      row: 9,
      col: 1,
    },
    {
      id: "rightElephant",
      type: "Elephant",
      img: "象",
      team: Team.black,
      row: 9,
      col: 2,
    },
    {
      id: "rightAdvisor",
      type: "Advisor",
      img: "士",
      team: Team.black,
      row: 9,
      col: 3,
    },
    {
      id: "general",
      type: "General",
      img: "將",
      team: Team.black,
      row: 9,
      col: 4,
    },
    {
      id: "leftAdvisor",
      type: "Advisor",
      img: "士",
      team: Team.black,
      row: 9,
      col: 5,
    },
    {
      id: "leftElephant",
      type: "Elephant",
      img: "象",
      team: Team.black,
      row: 9,
      col: 6,
    },
    {
      id: "leftHorse",
      type: "Horse",
      img: "馬",
      team: Team.black,
      row: 9,
      col: 7,
    },
    {
      id: "leftChariot",
      type: "Chariot",
      img: "車",
      team: Team.black,
      row: 9,
      col: 8,
    },
  ],
];

export default data;
