let data = [
  [
    { type: "Chariot", img: "車", team: "red" },
    { type: "Horse", img: "馬", team: "red" },
    { type: "Elephant", img: "相", team: "red" },
    { type: "Advisor", img: "仕", team: "red" },
    { type: "General", img: "帥", team: "red" },
    { type: "Advisor", img: "仕", team: "red" },
    { type: "Elephant", img: "相", team: "red" },
    { type: "Horse", img: "馬", team: "red" },
    { type: "Chariot", img: "車", team: "red" },
  ],
  Array(9).fill(null),
  [
    null,
    { type: "Cannon", img: "炮", team: "red" },
    null,
    null,
    null,
    null,
    null,
    { type: "Cannon", img: "炮", team: "red" },
    null,
  ],
  [
    { type: "Soldier", img: "兵", team: "red" },
    null,
    { type: "Soldier", img: "兵", team: "red" },
    null,
    { type: "Soldier", img: "兵", team: "red" },
    null,
    { type: "Soldier", img: "兵", team: "red" },
    null,
    { type: "Soldier", img: "兵", team: "red" },
  ],
  Array(9).fill(null),
  Array(9).fill(null),
  [
    { type: "Soldier", img: "卒", team: " black" },
    null,
    { type: "Soldier", img: "卒", team: " black" },
    null,
    { type: "Soldier", img: "卒", team: " black" },
    null,
    { type: "Soldier", img: "卒", team: " black" },
    null,
    { type: "Soldier", img: "卒", team: " black" },
  ],
  [
    null,
    { type: "Cannon", img: "炮", team: " black" },
    null,
    null,
    null,
    null,
    null,
    { type: "Cannon", img: "炮", team: " black" },
    null,
  ],
  Array(9).fill(null),
  [
    { type: "Chariot", img: "車", team: " black" },
    { type: "Horse", img: "馬", team: " black" },
    { type: "Elephant", img: "象", team: " black" },
    { type: "Advisor", img: "士", team: " black" },
    { type: "General", img: "將", team: " black" },
    { type: "Advisor", img: "士", team: " black" },
    { type: "Elephant", img: "象", team: " black" },
    { type: "Horse", img: "馬", team: " black" },
    { type: "Chariot", img: "車", team: " black" },
  ],
];

export default data;
